export type { Service, ServiceIconTone } from './service'
export type { Project } from './project'
export type { Testimonial } from './testimonial'
export type { Stat, StatColor } from './stat'
export type { NavItem } from './navigation'
export type { ProcessStep, ProcessTone } from './process'
export type { FooterColumn, FooterLink, SocialId, SocialLink } from './footer'
